#!/bin/sh

# userresources=$HOME/.Xresources
# usermodmap=$HOME/.Xmodmap
# userresourcesconfig="${XDG_CONFIG_HOME:-$HOME/.config}/Xresources"
# usermodmapconfig="${XDG_CONFIG_HOME:-$HOME/.config}/Xmodmap"
# sysresources=/etc/X11/xinit/.Xresources
# sysmodmap=/etc/X11/xinit/.Xmodmap

# # merge in defaults and keymaps
# [ -f $sysresources ] && { xrdb -merge $sysresources; }
# [ -f $sysmodmap ] && { xmodmap $sysmodmap; }
# [ -f "$userresources" ] && { xrdb -merge "$userresources"; }
# [ -f "$usermodmap" ] && { xmodmap "$usermodmap"; }
# [ -f "$userresourcesconfig" ] && { xrdb -merge "$userresourcesconfig"; }
# [ -f "$usermodmapconfig" ] && { xmodmap "$usermodmapconfig"; }

# start some nice programs

# if [ -d /etc/X11/xinit/xinitrc.d ] ; then
#  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
#   [ -x "$f" ] && . "$f"
#  done
#  unset f
# fi

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

# twm &
# xclock -geometry 50x50-1+1 &
# xterm -geometry 80x50+494+51 &
# xterm -geometry 80x20+494-0 &
# exec xterm -geometry 80x66+0+0 -name login

export $(dbus-launch)
exec i3
